[package]
name = "hippo-swap"
version = "0.0.1"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "7f967d7d8d230dcf10bd3a8d25d5d3ed9f96b8f4" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "7f967d7d8d230dcf10bd3a8d25d5d3ed9f96b8f4" }
CoinList = { git = "https://github.com/hippospace/aptos-coin-list.git", subdir = "", rev = "bf414da2ee21cd9c1660a19f7b305eab2fa830af" }

[addresses]
hippo_swap = "a61e1e86e9f596e483283727d2739ba24b919012720648c29380f9cd0a96c11a"
