[package]
name = "hippo-swap"
version = "0.0.1"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "971c160079263a8d3e1d2503a570b01ecaaf10ba" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "971c160079263a8d3e1d2503a570b01ecaaf10ba" }
CoinList = { git = "https://github.com/hippospace/aptos-coin-list.git", subdir = "", rev = "e74926a4e12dbffa783fd7bfad79641ce3e2f6a0" }

[addresses]
hippo_swap = "a61e1e86e9f596e483283727d2739ba24b919012720648c29380f9cd0a96c11a"
